branch-defaults:
  master:
    environment: jordangarcia-dot-me-prod
    group_suffix: null
environment-defaults:
  jordangarcia-dot-me-dev:
    branch: null
    repository: null
global:
  application_name: jordangarcia-dot-me
  default_ec2_keyname: null
  default_platform:
    arn:aws:elasticbeanstalk:us-east-1::platform/Docker running on
    64bit Amazon Linux/2.12.3
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
