branch-defaults:
  master:
    environment: arickho-dot-com-prod
  use-next-js:
    environment: arickho-dot-com-dev
    group_suffix: null
global:
  application_name: arickho-dot-com
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 18.06.1-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
