branch-defaults:
  master:
    environment: arickho-dot-com-prod
    group_suffix: null
environment-defaults:
  arickho-dot-com-dev:
    branch: null
    repository: null
global:
  application_name: arickho-dot-com
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Docker running on
    64bit Amazon Linux/2.12.3
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
