version: 2
jobs:
  install_dependencies:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install --silent --progress=false
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  build_app:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
  build_and_deploy_to_dev_s3:
    docker:
      - image: 'circleci/node:8.12.0'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build application
          command: NODE_ENV=staging npm run build
      - run:
          name: Install aws cli
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            awscli-bundle/install -b ~/bin/aws
      - run:
          name: Deploy to S3
          command: ~/bin/aws s3 sync out/ s3://jordangarcia.me --delete --acl public-read
  build_and_deploy_to_dev_eb:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - checkout
      - run:
          name: Install awsebcli
          command: |
            sudo pip install awsebcli --upgrade
      - run:
          name: Deploy to Dev EB
          command: eb deploy jordangarcia-dot-me-dev
  build_and_deploy_to_prod_s3:
    docker:
      - image: 'circleci/node:8.12.0'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build application
          command: NODE_ENV=production npm run build
      - run:
          name: Install aws cli
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            awscli-bundle/install -b ~/bin/aws
      - run:
          name: Deploy to S3
          command: ~/bin/aws s3 sync out/ s3://jordangarcia.me --delete --acl public-read
  build_and_deploy_to_prod_eb:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - checkout
      - run:
          name: Install awsebcli
          command: |
            sudo pip install awsebcli --upgrade
      - run:
          name: Deploy to Prod EB
          command: eb deploy jordangarcia-dot-me-prod

workflows:
  version: 2
  build_web_workflow:
    jobs:
      - install_dependencies
      - build_app:
          requires:
            - install_dependencies
          filters:
            branches:
              ignore:
                - master
      - build_and_deploy_to_dev_s3:
          requires:
            - install_dependencies
          filters:
            branches:
              only: develop
      - build_and_deploy_to_dev_eb:
          requires:
            - install_dependencies
          filters:
            branches:
              only: develop
      - build_and_deploy_to_prod_s3:
          requires:
            - install_dependencies
          filters:
            branches:
              only: master
      - build_and_deploy_to_prod_eb:
          requires:
            - install_dependencies
          filters:
            branches:
              only: master
