version: 2
jobs:
  deploy_to_dev_s3:
    docker:
      - image: "circleci/node:8.12.0"
    steps:
      - checkout
      - run: npm install --silent --progress=false
      - run: npm run export
      - run:
          name: Install aws cli
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            awscli-bundle/install -b ~/bin/aws
      - run:
          name: Deploy to S3
          command: |
            ~/bin/aws s3 sync out/.next/ s3://jordangarcia.dev.me/_next --delete
            ~/bin/aws s3 sync out/static/ s3://jordangarcia.dev.me/static --delete
            ~/bin/aws s3 sync out/404.html s3://jordangarcia.dev.me/404.html --delete
            ~/bin/aws s3 cp out/index.html s3://jordangarcia.dev.me/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read

  deploy_to_prod_s3:
    docker:
      - image: "circleci/node:8.12.0"
    steps:
      - checkout
      - run: npm install --silent --progress=false
      - run: npm run export
      - run:
          name: Install aws cli
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            awscli-bundle/install -b ~/bin/aws
      - run:
          name: Deploy to S3
          command: |
            ~/bin/aws s3 sync out/.next/ s3://jordangarcia.me/_next --delete
            ~/bin/aws s3 sync out/static/ s3://jordangarcia.me/static --delete
            ~/bin/aws s3 sync out/404.html s3://jordangarcia.me/404.html --delete
            ~/bin/aws s3 cp out/index.html s3://jordangarcia.me/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read

workflows:
  version: 2
  build_web_workflow:
    jobs:
      - deploy_to_dev_s3:
          filters:
            branches:
              only: develop

      - deploy_to_prod_s3:
          filters:
            branches:
              only: master
