version: 2
jobs:
  install_dependencies:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install --silent --progress=false
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  build_app:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
  build_and_deploy:
    docker:
      - image: 'circleci/node:8.12.0'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build application
          command: npm run build
      - run:
          name: Update apt-get
          command: sudo apt-get update -y
      - run:
          name: Install aws cli and elastic beanstalk cli
          command: sudo apt-get install -y awscli awsebcli
      - run:
          name: Deploy to S3
          command: aws s3 sync build/ s3://arickho-dot-com-docker
      - run:
          name: Deploy to Elastic Beanstalk
          command: eb deploy production

workflows:
  version: 2
  build_web_workflow:
    jobs:
      - install_dependencies
      - build_app:
          requires:
            - install_dependencies
          filters:
            branches:
              ignore:
                - master
      - build_and_deploy:
          requires:
            - install_dependencies
          filters:
            branches:
              only: master
